### ISSUE TITLE
Hide affter Instance launch

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#100]
### What's frustrating? 😳
When instance launched, launcher still visible on desktop.

### Solution you'd like 🥰
Launcher should be hidden to tray.

### Tasks 📃
 - [x] Add to host confing
 - [x] Hook to launcher
 - [x] Add to settings in UI
 - [ ] Add to installation overrides
