### ISSUE TITLE
Full support for desktop shortcuts

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#104]
### What's frustrating? 😳
At this point we have full support for triggering installation launch through the `protocolHandler` (eq. deep linking). We need to create shortcuts on desktop, menus, applacations and etc.

### Solution you'd like 🥰
Create scripts for each platform to create installation shortcut with title and icon. But firstly close #51 and #102 

### Tasks 📃
 - [ ] Close #51 
 - [ ] Close #102 
 - [ ] Create script for Windows platform
 - [ ] Create script for Darwin platform
 - [ ] Create script for Linux platforms ?
 - [ ] Add new action reducer for `Host`
 - [ ] Add to context menu on installation
