### ISSUE TITLE
MultiAccount support

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#109]
### What's frustrating? 😳
Fast switching between MultiAccounts is still not supported!

### Solution you'd like 🥰
Implement multi account store in UI and sync it with host.

### Tasks 📃
 - [ ] Create multi account store in ui
 - [ ] Create gate with host to sync accounts
 - [ ] Create UI for switching
