### ISSUE TITLE
Estimated time calc

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#40]
### What's frustrating? 😳
For better ux its need to add an estimated time calculation of downloading

### Solution you'd like 🥰
Create one download queue and calculate time by average download speed and total amount of files.

### Tasks 📃
 - [x] Stash all files to one download queue
 - [x] Calculate estimated time, based on average load speed
 - [x] Bring remaining time to UI
