### ISSUE TITLE
Icons for installations

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#51]
### What's frustrating? 😳
Its need of icons for each installation

### Tasks 📃
 - [ ] Add support to **InstallationsManager**
 - [ ] Render to installations list
 - [ ] Create picker for **VersionChooser**
