### ISSUE TITLE
Support installation ready state

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#77]
### What's frustrating? 😳
Actually you dont know the ready state of each installation, to precalc loading time of it.

### Solution you'd like 🥰
Maybe add some signals or labels of ready state for each installation?!

### Tasks 📃
 - [ ] Support ready state check on host
 - [ ] Add ready state reducing on ui
 - [ ] Add tags for ui
