### ISSUE TITLE
Feature request to remote control

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#79]
### How does it look like? 🤩
The host (launcher on your PC) registers in tjmc wss network as a host, with your credentials. Then you can sign in on the web client (or on the other host-client app) and remotely control the host.

### Tasks 📃
 - [ ] create tjmc wss network
 - [ ] create tjmc database of registered hosts
 - [ ] implement connector for host
 - [ ] implement connector for client and rebuild web version
 - [ ] finalize reducers of state management
