### ISSUE TITLE
Support deep reinstall

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#83]
### What's frustrating? 😳
When migrating from older launcher versions or just modifying some kernel files of minecraft, its normally that launch will be crashed. There is a strictly need of full reinstall of all dependencies for this version.

### Solution you'd like 🥰
Implement Force check with deep comparison (including version manifest rebuild) or totaly rewrite all the files (bad and long way).

### Tasks 📃
 - [x] Support deep scan in worker core
 - [x] Create shortucts for deep scan
 - [ ] Add to ui context menu
