### ISSUE TITLE
Support custom background

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#86]
### What's frustrating? 😳
Its need to support background changing option. Maybe multiple with dynamic changes or for each installation its own?

### Solution you'd like 🥰
Remove skin edit from settings (totaly useless) and create a tab with background customization

### Tasks 📃
 - [ ] Support in global state
 - [ ] Create img transitions
 - [ ] Create setting tab
