### ISSUE TITLE
Problem with focus trap

### ISSUE THREAD

**Issue by MakAndJo** [tjmcraft/TJMC-Launcher#92]
### What's frustrating? 😳
Opening a new modal/alert or switching a layer causes problems with focus trap. Keydown events, such as Tab navigation or hotkeys are handled incorrect way, cause bottom layer handles them too. And its frustrating and sometimes seems like invalid.

### Solution you'd like 🥰
Create a focus trap for modals and layers. And maybe improve aria tab navigation in modals?!

### Tasks 📃
 - [x] Create focus trap hook
 - [x] Hook modals/layers
 - [x] Enhance aria tab navigation
